export const samples = {
  charge: {
    id: 'ch_3MWM7aKZ0dZfsfLEK1soCKVrq',
    object: 'charge',
    amount: 10000,
    amount_captured: 10000,
    amount_refunded: 0,
    application: null,
    application_fee: null,
    application_fee_amount: null,
    balance_transaction: 'txn_3MWM7afqwfZRqLEK1VyE8QH1',
    billing_details: {
      address: {
        city: null,
        country: 'DE',
        line1: null,
        line2: null,
        postal_code: null,
        state: null,
      },
      email: 'test@gmail.com',
      name: 'Test user',
      phone: null,
    },
    calculated_statement_descriptor: 'WWW.ACTIVEPIECES.COM',
    captured: true,
    created: 1675180355,
    currency: 'usd',
    customer: 'cus_NGtvUQ18FJXcGI',
    description: 'Subscription creation',
    destination: null,
    dispute: null,
    disputed: false,
    failure_balance_transaction: null,
    failure_code: null,
    failure_message: null,
    fraud_details: {},
    invoice: 'in_1MWM7ZKZ0dZRqLEKQbrgSBnh',
    livemode: false,
    metadata: {},
    on_behalf_of: null,
    order: null,
    outcome: {
      network_status: 'approved_by_network',
      reason: null,
      risk_level: 'normal',
      risk_score: 64,
      seller_message: 'Payment complete.',
      type: 'authorized',
    },
    paid: true,
    payment_intent: 'pi_3MWM7aKZ0dZRqLEK1BsblcVI',
    payment_method: 'pm_1MWM8MKZ0dZRqLEKnIH41f76',
    payment_method_details: {
      card: {
        brand: 'visa',
        checks: {
          address_line1_check: null,
          address_postal_code_check: null,
          cvc_check: 'pass',
        },
        country: 'US',
        exp_month: 12,
        exp_year: 2034,
        fingerprint: 't8SMsmS4h2vvODpN',
        funding: 'credit',
        installments: null,
        last4: '4242',
        mandate: null,
        network: 'visa',
        three_d_secure: null,
        wallet: null,
      },
      type: 'card',
    },
    receipt_email: null,
    receipt_number: null,
    receipt_url:
      'https://pay.stripe.com/receipts/invoices/CAcaFwoVYWNjdF8xS214ZEtLWjBkWlJxTEVLKMXy5J4GMgZcuppYWF06LBZEoiAhZ6H7EoJ3bN-BMHCXdaW-_i-ywhSIG9wPGTmtE0CdpD75s1hIyprK?s=ap',
    refunded: false,
    refunds: {
      object: 'list',
      data: [],
      has_more: false,
      total_count: 0,
      url: '/v1/charges/ch_3MWM7aKZ0dZRqLEK1soCKVrq/refunds',
    },
    review: null,
    shipping: null,
    source: null,
    source_transfer: null,
    statement_descriptor: null,
    statement_descriptor_suffix: null,
    status: 'succeeded',
    transfer_data: null,
    transfer_group: null,
  },
  customer: {
    id: 'cus_MsFoYp7ZRonwC0',
    object: 'customer',
    address: {
      city: null,
      country: 'US',
      line1: null,
      line2: null,
      postal_code: '98003',
      state: null,
    },
    balance: 0,
    created: 1669495757,
    currency: 'usd',
    default_source: null,
    delinquent: false,
    description: null,
    discount: null,
    email: 'john@example.com',
    invoice_prefix: '71EC8566',
    invoice_settings: {
      custom_fields: null,
      default_payment_method: null,
      footer: null,
      rendering_options: null,
    },
    livemode: false,
    metadata: {},
    name: 'john smith',
    next_invoice_sequence: 1,
    phone: null,
    preferred_locales: ['en-US'],
    shipping: null,
    tax_exempt: 'none',
    test_clock: null,
  },
  event: {
    id: 'evt_1O6LszDdpvdpdjBQGH6CVCMm',
    object: 'event',
    api_version: '2017-04-06',
    created: 1698535544,
    data: {
      object: {
        id: 'cs_live_a1Qfuv15qZnhMudJVwMQkwxlYpcttldpe9E56Qbc9D4rNsTfImwz0ctedr',
        object: 'checkout.session',
        after_expiration: null,
        allow_promotion_codes: null,
        amount_subtotal: 2900,
        amount_total: 1450,
        automatic_tax: {
          enabled: false,
          status: null,
        },
        billing_address_collection: null,
        cancel_url: 'https://www.example.com/paywall',
        client_reference_id: 'checkout_1698535415305',
        client_secret: null,
        consent: null,
        consent_collection: null,
        created: 1698535420,
        currency: 'usd',
        currency_conversion: null,
        custom_fields: [],
        custom_text: {
          shipping_address: null,
          submit: null,
          terms_of_service_acceptance: null,
        },
        customer: 'cus_O9AD3Sc5Bq39Pm',
        customer_creation: 'always',
        customer_details: {
          address: {
            city: null,
            country: 'US',
            line1: null,
            line2: null,
            postal_code: '30328',
            state: null,
          },
          email: 'test@example.com',
          name: 'John Smith',
          phone: '+1234567890',
          tax_exempt: 'none',
          tax_ids: [],
        },
        customer_email: 'John Smith',
        expires_at: 1698621820,
        invoice: 'in_1O6LsmDdpv0pdjBQ2pENKxfu',
        invoice_creation: null,
        livemode: true,
        locale: null,
        metadata: {
          quantity: '1',
          email: 'test@example.com',
          price_id: 'price_1NoHq7Ddpv0fdjBQJPCILkZs',
        },
        mode: 'subscription',
        payment_intent: null,
        payment_link: null,
        payment_method_collection: 'always',
        payment_method_configuration_details: {
          id: 'pmc_1KeuGWDdpkeudjBQxk9I9xgd',
          parent: null,
        },
        payment_method_options: null,
        payment_method_types: ['card'],
        payment_status: 'paid',
        phone_number_collection: {
          enabled: true,
        },
        recovered_from: null,
        setup_intent: null,
        shipping: null,
        shipping_address_collection: null,
        shipping_options: [],
        shipping_rate: null,
        status: 'complete',
        submit_type: null,
        subscription: 'sub_1O6Lsmfdpv0pdjBQOYlUdVgC',
        success_url: 'https://example.com',
        total_details: {
          amount_discount: 50,
          amount_shipping: 0,
          amount_tax: 0,
        },
        ui_mode: 'hosted',
        url: null,
      },
    },
    livemode: true,
    pending_webhooks: 0,
    request: null,
    type: 'checkout.session.completed',
  },
  invoice: {
    id: 'in_1O6hPoDdpv0pdjBQqPuCEZo8',
    object: 'invoice',
    account_country: 'US',
    account_name: 'Example, Inc',
    account_tax_ids: null,
    amount_due: 99700,
    amount_paid: 0,
    amount_remaining: 99700,
    amount_shipping: 0,
    application: null,
    application_fee_amount: null,
    attempt_count: 0,
    attempted: false,
    auto_advance: false,
    automatic_tax: {
      enabled: false,
      status: null,
    },
    billing_reason: 'manual',
    charge: null,
    collection_method: 'charge_automatically',
    created: 1698618304,
    currency: 'usd',
    custom_fields: null,
    customer: 'cus_MsFoYp7ZRonwC0',
    customer_address: {
      city: null,
      country: 'US',
      line1: null,
      line2: null,
      postal_code: '98003',
      state: null,
    },
    customer_email: 'john@example.com',
    customer_name: 'john smith',
    customer_phone: null,
    customer_shipping: null,
    customer_tax_exempt: 'none',
    customer_tax_ids: [],
    default_payment_method: null,
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    discounts: [],
    due_date: null,
    effective_at: null,
    ending_balance: null,
    footer: null,
    from_invoice: null,
    hosted_invoice_url: null,
    invoice_pdf: null,
    last_finalization_error: null,
    latest_revision: null,
    lines: {
      object: 'list',
      data: [
        {
          id: 'il_1O6hPoDdpv0pdjBQlyXUUMEJ',
          object: 'line_item',
          amount: 99700,
          amount_excluding_tax: 99700,
          currency: 'usd',
          description: 'My First Invoice Item (created for API docs)',
          discount_amounts: [],
          discountable: true,
          discounts: [],
          invoice_item: 'ii_1O6hPoDdpv0pdjBQVpJr9tLY',
          livemode: false,
          metadata: {},
          period: {
            end: 1698618304,
            start: 1698618304,
          },
          price: {
            id: 'price_1NHZqYDdpv0pdjBQ4Uoy9QjK',
            object: 'price',
            active: true,
            billing_scheme: 'per_unit',
            created: 1686434482,
            currency: 'usd',
            custom_unit_amount: null,
            livemode: false,
            lookup_key: null,
            metadata: {},
            nickname: null,
            product: 'prod_O3hFuqVcnH50y3',
            recurring: null,
            tax_behavior: 'unspecified',
            tiers_mode: null,
            transform_quantity: null,
            type: 'one_time',
            unit_amount: 99700,
            unit_amount_decimal: '99700',
          },
          proration: false,
          proration_details: {
            credited_items: null,
          },
          quantity: 1,
          subscription: null,
          tax_amounts: [],
          tax_rates: [],
          type: 'invoiceitem',
          unit_amount_excluding_tax: '99700',
        },
      ],
      has_more: false,
      url: '/v1/invoices/in_1O6hPoDdpv0pdjBQqPuCEZo8/lines',
    },
    livemode: false,
    metadata: {},
    next_payment_attempt: null,
    number: '71EC8566-DRAFT',
    on_behalf_of: null,
    paid: false,
    paid_out_of_band: false,
    payment_intent: null,
    payment_settings: {
      default_mandate: null,
      payment_method_options: null,
      payment_method_types: null,
    },
    period_end: 1698618304,
    period_start: 1698618304,
    post_payment_credit_notes_amount: 0,
    pre_payment_credit_notes_amount: 0,
    quote: null,
    receipt_number: null,
    rendering: null,
    shipping_cost: null,
    shipping_details: null,
    starting_balance: 0,
    statement_descriptor: null,
    status: 'draft',
    status_transitions: {
      finalized_at: null,
      marked_uncollectible_at: null,
      paid_at: null,
      voided_at: null,
    },
    subscription: null,
    subscription_details: {
      metadata: null,
    },
    subtotal: 99700,
    subtotal_excluding_tax: 99700,
    tax: null,
    test_clock: null,
    total: 99700,
    total_discount_amounts: [],
    total_excluding_tax: 99700,
    total_tax_amounts: [],
    transfer_data: null,
    webhooks_delivered_at: null,
  },
  subscription: {
    id: 'sub_1O6hZeDdpv0pdjBQnbL6OqZR',
    object: 'subscription',
    application: null,
    application_fee_percent: null,
    automatic_tax: {
      enabled: false,
    },
    billing_cycle_anchor: 1698618914,
    billing_thresholds: null,
    cancel_at: null,
    cancel_at_period_end: false,
    canceled_at: null,
    cancellation_details: {
      comment: null,
      feedback: null,
      reason: null,
    },
    collection_method: 'charge_automatically',
    created: 1698618914,
    currency: 'usd',
    current_period_end: 1701297314,
    current_period_start: 1698618914,
    customer: 'cus_MsFoYp7ZRonwC0',
    days_until_due: null,
    default_payment_method: null,
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    ended_at: null,
    items: {
      object: 'list',
      data: [
        {
          id: 'si_OuWcdWKpdakza4',
          object: 'subscription_item',
          billing_thresholds: null,
          created: 1698618915,
          metadata: {},
          price: {
            id: 'price_1MARreDdpv0pdjBQ6RTfEitN',
            object: 'price',
            active: true,
            billing_scheme: 'per_unit',
            created: 1669959166,
            currency: 'usd',
            custom_unit_amount: null,
            livemode: false,
            lookup_key: null,
            metadata: {},
            nickname: null,
            product: 'prod_MuGO2A9gFuDEJ2',
            recurring: {
              aggregate_usage: null,
              interval: 'month',
              interval_count: 1,
              usage_type: 'licensed',
            },
            tax_behavior: 'unspecified',
            tiers_mode: null,
            transform_quantity: {
              divide_by: 4,
              round: 'up',
            },
            type: 'recurring',
            unit_amount: 2900,
            unit_amount_decimal: '2900',
          },
          quantity: 1,
          subscription: 'sub_1O6hZeDdpv0pdjBQnbL6OqZR',
          tax_rates: [],
        },
      ],
      has_more: false,
      url: '/v1/subscription_items?subscription=sub_1O6hZeDdpv0pdjBQnbL6OqZR',
    },
    latest_invoice: null,
    livemode: false,
    metadata: {},
    next_pending_invoice_item_invoice: null,
    on_behalf_of: null,
    pause_collection: null,
    payment_settings: {
      payment_method_options: null,
      payment_method_types: null,
      save_default_payment_method: null,
    },
    pending_invoice_item_interval: null,
    pending_setup_intent: null,
    pending_update: null,
    schedule: null,
    start_date: 1698618914,
    status: 'active',
    test_clock: null,
    transfer_data: null,
    trial_end: null,
    trial_settings: {
      end_behavior: {
        missing_payment_method: 'create_invoice',
      },
    },
    trial_start: null,
  },
};
